---
- name: Main Deploy File
  hosts: astcc_servers
  become: yes
  vars_prompt:
    - name: "mysqlpass"
      prompt: "enter mysqlpass:"
    - name: "keypass"
      prompt: "enter keypass"

  roles:
    - tls_asterisk
